site_name: KEG Zettelkasten for Jared Rickert (jlrickert)
site_url: https://zet.jlrickert.me
repo_name: jlrickert/zet
repo_url: https://github.com/jlrickert/zet
edit_uri: edit/main/docs
site_author: Jared Rickert (jaredrickert52@gmail.com)
site_description: >-
  Hi I'm Jared. This is my personal **zettelkasten** KEG site. It contains stuff
  on pretty much any topic I feel like writing about, mostly about [baking](292)
  and tech how too. You can think of it as my own personal stack overflow or
  arch wiki. The latest additions and changes are always [indexed](dex).

  A word of caution is that these are raw notes. They may be inaccurate, messy,
  and/or plain misleading. Please don't quote me here as I may not still hold
  the same opinion on the subject. That is what my [blog] is for.

  The reason that I make these notes available is that they may be helpful to
  some one out there.
use_directory_urls: false
theme:
  name: readthedocs
  analytics:
    gtag: G-WXQ3PHET4N
  titles_only: true
  highlightjs: true
  hljs_languages:
    - TypeScript
    - Svelte
    - Shell
    - SCSS
    - SAS
    - Rust
    - Ruby
    - R
    - Python
    - PostgreSQL
    - JavaScript
    - Go
    - Java
    - JSON
    - TOML
    - hlsl
    - Haskell
    - HTTP
    - GraphQL
    - Dockerfile
    - DNS Zone file
    - Django
    - Diff
    - Dart
    - CSS
    - CMake
    - C
    - C++
    - Bash
    - Awk
  # features:
  #   - content.action.edit
  #   - content.action.view
  #   - search.suggest
  #   - search.highlight
  #   - search.share
  #   - navigation.instant
  #   - navigation.instant.prefetch
extra:
  analytics:
    provider: google
    property: G-WXQ3PHET4N
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our <a
            href="https://github.com/jlrickert/zet/issues/new" target="_blank"
            rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins:
  - search
  - meta-manager:
      meta_filename: meta.yaml

markdown_extensions:
  - footnotes
  - fenced_code
  - tables
  - admonition
  - sane_lists
  - smarty
  - markdown_checklist.extension
